Add package name to RustBufferI if it needs it
NordSecurity/uniffi-bindgen-go pull request #44
Opened 2024-03-08 15:15 UTC by kegsay

Fixes https://github.com/NordSecurity/uniffi-bindgen-go/issues/43

Struggling to write a fixture for this currently. This helps to make uniffi-bindgen-go produce code that compiles.

2024-03-12 16:20 UTC, arg0d commented
I'm trying to wrap my head around when does this happen. Is there a simple way to repro this inside the tests? I think there are already some tests for "external" types `ext_types_test.go`.

2024-03-12 17:47 UTC, kegsay commented
It only happens on async functions when the value being returned is in another package. In that case, both packages have `RustBufferI` types and the compiler complains as the generated code uses both types when it should be choosing one and sticking with it.

There isn't a simple way to reproduce the test due to #45 - I could probably write a test in a completely separate test package and then `go test` that?

2024-03-13 08:30 UTC, arg0d commented
I can reproduce #45, but this PR does not seem to do anything for #45, I still get the same error with these changes.

2024-03-13 12:01 UTC, kegsay commented
It won't do anything for #45. This PR is fixing #43.

2024-03-14 10:02 UTC, kegsay commented
Yup, I have a working regression test now in a new package `uniffi_go_issue43`. The test itself just does:
```
#[uniffi::export]
async fn get_async_external_type() -> uniffi_go_issue45::Record {
    uniffi_go_issue45::Record {
        id: "foo".to_string(),
        tag: "bar".to_string(),
    }
}
```
which requires this PR to produce code that compiles, which produces a `completeFunc` of:
```go
		func(handle *C.void, status *C.RustCallStatus) issue45.RustBufferI {
			// completeFunc
			return C.ffi_uniffi_go_issue43_rust_future_complete_rust_buffer(unsafe.Pointer(handle), status)
		},
```
whereas without #44 it would just be `func(handle *C.void, status *C.RustCallStatus) RustBufferI {` which compile errors on the `liftFunc`: `type func(rb issue45.RustBufferI) issue45.Record of issue45.FfiConverterTypeRecordINSTANCE.Lift does not match inferred type func(RustBufferI) U for func(T) Ucompiler[CannotInferTypeArgs](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#CannotInferTypeArgs)`.

2024-03-14 10:22 UTC, kegsay commented
Rebased as #46 landed. It should be pretty clear now!

2024-03-14 12:19 UTC, arg0d commented
Nice work!

I finally understand why this error only happens with async :sweat_smile: My initial reaction was that this should also happen with regular functions, e.g.
```golang
func GetAsyncExternalType() issue45.Record {
	return issue45.FfiConverterTypeRecordINSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) RustBufferI {
		return C.uniffi_uniffi_go_issue43_fn_func_get_async_external_type(_uniffiStatus)
	}))
}
```
In this example there is also a type mismatch between what `issue45.FfiConverterTypeRecordINSTANCE.Lift` expects, and what `rustCall` returns. But I assume in this case Go's interface duck typing kicks in, and allows an implicit conversion from `issue43.RustBufferI` into `issue45.RustBufferI`.

Contrast that with async code, where `issue43.RustBufferI` and `issue45.RustBufferI` are parameters to a generic function `func uniffiRustCallAsyncWithResult[T any, U any] ..`, and interface duck typing rules do not apply - compiler expects identical types for generic parameters.

2024-03-14 12:20 UTC, arg0d requested changes

2024-03-14 12:20 UTC, arg0d commented on bindgen/src/gen_go/mod.rs
> +    pub fn maybe_namespace(type_: &impl AsType) -> Result<String, askama::Error> {
I would implement this as part of `ffi_type_name` function itself, that would be more robust.
```diff
diff --git a/bindgen/src/gen_go/mod.rs b/bindgen/src/gen_go/mod.rs
index 1c1c638..9781ea7 100644
--- a/bindgen/src/gen_go/mod.rs
+++ b/bindgen/src/gen_go/mod.rs
@@ -465,11 +465,14 @@ pub mod filters {
     }
 
     /// FFI type name to be used to reference cgo types
-    pub fn ffi_type_name<T: Clone + Into<FfiType>>(type_: &T) -> Result<String, askama::Error> {
+    pub fn ffi_type_name(type_: &Type) -> Result<String, askama::Error> {
         let ffi_type: FfiType = type_.clone().into();
         let result = match ffi_type {
             FfiType::RustArcPtr(_) => "unsafe.Pointer".into(),
-            FfiType::RustBuffer(_) => "RustBufferI".into(),
+            FfiType::RustBuffer(_) => match type_ {
+                Type::External { namespace, .. } => format!("{}.RustBufferI", namespace),
+                _ => "RustBufferI".into(),
+            },
             _ => format!("C.{}", oracle().ffi_type_label(&ffi_type)),
         };
         Ok(result)
```

2024-03-14 13:13 UTC, arg0d approved these changes
Nice work, thanks for contributing!

2024-03-14 13:13 UTC, merged